### ISSUE TITLE
Progess on iOS port?

### ISSUE THREAD

**Issue by HeyWrecker** [KumarSunil007/phonegap-jack-reader-plugin#1]
It looks like it's been a while since your last update. Have you made any further progress on the iOS version?

**Comment by KumarSunil007** [comment]
Thanks for reminding me. I have everything ready for IOS. I was just not getting a proper time to provide new updates on this repo. Soon I will upload new code for both platform. Thanks for your patience.

**Comment by KumarSunil007** [comment]
Hey, Thanks for patience . I had updated repo for IOS as well. Please use plugin and submit report for errors (if any).
