### ISSUE TITLE
Any example for Swift

### ISSUE THREAD

**Issue by hiravsampat** [KumarSunil007/phonegap-jack-reader-plugin#2]
I am having problem using this library with swift 3 in my project.
Can this be used with swift 3 ?
If yes, can you provide an example for the same.

**Comment by KumarSunil007** [comment]
You may be facing issue for linker error. Just remove library during build and add it again. Hope it will work fine. If you further need any help, please let me know

**Comment by Darkmadda** [comment]
KumarSunil, can you provide more details on the linker error. i'm getting it and removing it and adding it only causes more problems and i'm unable to build.

**Comment by KumarSunil007** [comment]
It is library issue. The vendor was not working on library development from
long time because of that we are getting linker error and bitcode error. By
removing and adding library you can create build.

**Comment by Darkmadda** [comment]
ok for others out there I figured out how to get past the error. remove the library from the framework then copy the library back into the project, but here is the key. Don't add it back as a framework in the settings, just have the file in the project accessible to the compiler. I was adding it to the frameworks list after re-adding it to the project and that will cause linker errors.
