### ISSUE TITLE
Device ready event not occurring in presence of this plugin

### ISSUE THREAD

**Issue by Maunga** [KumarSunil007/phonegap-jack-reader-plugin#3]
Is there a specific way that this plugin should be installed? I've been installing it as follows

cordova plugin add https://github.com/KumarSunil007/phonegap-jack-reader-plugin

Then my app's deviceready event never occurs.

**Comment by KumarSunil007** [comment]
it will not effect device ready event, also if you read docs for device ready event, it is independent of all plugin and scripts. ( if you are facing this issue on browser, then it generally happens, it will not occur on ios and android platform)

**Comment by Maunga** [comment]
I've also tried compiling with Phonegap build with no luck. A more detailed step by step guide on how to implement this plugin would be most peferrable not just the Javascript code
