### ISSUE TITLE
How install plugin?

### ISSUE THREAD

**Issue by Exzce** [KumarSunil007/phonegap-jack-reader-plugin#5]

**Comment by KumarSunil007** [comment]
use phonegap plugin add https://github.com/KumarSunil007/phonegap-jack-reader-plugin.git
or cordova plugin add https://github.com/KumarSunil007/phonegap-jack-reader-plugin.git

**Comment by Maunga** [comment]
Hi KumarSunil007, I'm still facing challenges with the installation of this plugin. Do you mind giving a more detailed description of how to install it. Obviusly we run cordova plugin add https://github.com/KumarSunil007/phonegap-jack-reader-plugin.git. However, I feel the intricate details are being left out. Please help out.

**Comment by sustaintopervail** [comment]
Hi Kumar,

I installed the plugin successfully and make it work, but problem I am facing is that it works only once i.e. when application is started. Card swiped is captured only first time in the cordova app, whereas in android studio LogCat, I can still see the multiple readings of swipes done afterwards. 

Do you have any idea why there is such issue? may be a quick hack or something can really help.

Thanks,
