### ISSUE TITLE
which reader do you support/recommend

### ISSUE THREAD

**Issue by stccorp** [KumarSunil007/phonegap-jack-reader-plugin#7]
this is the only reader I can find(https://www.ebay.com/itm/3-5mm-Headphone-Jack-Mini-Magnetic-Phone-Card-Reader-Support-iOS-8-0-and-Android/263774433460?epid=1576395335&hash=item3d6a2e70b4:m:mYW9wiVxgYw_io0o_tkmHGA)

do you have a specific reader that you know the library will work with? 

Thank you

**Comment by KumarSunil007** [comment]
it will work with all reader that are not sending data into encrypted format. You can modify code and then you can see output from reader, based on your requirement you can extract necessary information from that data.
